apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: actions-openbao
  annotations:
    github.com/project-slug: mattjmorrison-homelab/actions-openbao
spec:
  type: library
  owner: mattjmorrison-homelab
  lifecycle: experimental
  system: ci
